### ISSUE TITLE
aapt is outdated

### ISSUE THREAD

**Issue by mittorn** [skyleecm/android-build-tools-for-arm#1]
It does not work with recent apktool

**Comment by skyleecm** [comment]
hi  mittorn ,
 I have tried a newly compiled aapt, but it cannot run successfully.

it will fail with illegal instruction. It maybe the same/related issue as [issue 58663](https://code.google.com/p/android/issues/detail?id=58663) or
[issue 58449](https://code.google.com/p/android/issues/detail?id=58449)

**Comment by mittorn** [comment]
What instruction is at signal address?
You can run it with gdb and get disassemble around crash point.
Other possible solution is remove '--forced-package-id' from arguments and use old version, it helps.

**Comment by skyleecm** [comment]
The ALOG_ASSERT in system/core/libutils/VectorImpl.cpp is causing illegal instruction when running aapt, commenting it off seems to fix the aapt crash issue.

I have checked in a new branch with the binaries and shared libs. [build-21](https://github.com/skyleecm/android-build-tools-for-arm/tree/build-21)

[build-21.md](https://github.com/skyleecm/android-build-tools-for-arm/blob/build-21/build-21.md) has the details.

**Comment by skyleecm** [comment]
hopefully, this will be running well, I have not tested it much.

**Comment by skyleecm** [comment]
will be awol for ..

**Comment by skyleecm** [comment]
so far so good (in Debian jessie).
Given that Debian stretch provides aapt for arm, https://packages.debian.org/stable/aapt
, there will not be any more updates here.
